# Generated by Django 5.0.1 on 2024-03-11 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainProject', '0001_initial'),
        ('signup_login', '0005_seller_proof_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, default='', max_length=200, null=True)),
                ('image', models.ImageField(upload_to='uploads/products/')),
                ('stock', models.IntegerField()),
                ('available', models.BooleanField(default=True)),
                ('subcategory', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainProject.category')),
                ('seller_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='signup_login.seller')),
            ],
        ),
    ]
