# Generated by Django 5.0.1 on 2024-03-26 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainProject', '0003_alter_category_id'),
        ('signup_login', '0006_alter_customer_id_alter_seller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='signup_login.customer')),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainProject.product')),
            ],
        ),
    ]
