# Generated by Django 5.0.1 on 2024-03-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainProject', '0008_remove_order_id_alter_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
