# Generated by Django 5.0.1 on 2024-03-28 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainProject', '0009_order_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='desciption',
            new_name='description',
        ),
    ]
