# Generated by Django 5.0.1 on 2024-03-30 05:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainProject', '0010_rename_desciption_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 3, 30, 5, 4, 9, 867099, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
