# Generated by Django 5.0.1 on 2024-03-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
