# Generated by Django 5.0.1 on 2024-03-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_login', '0002_alter_customer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=500)),
                ('company_name', models.CharField(max_length=255)),
            ],
        ),
    ]
