# Generated by Django 5.0.1 on 2024-03-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_login', '0004_alter_seller_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='proof_img',
            field=models.ImageField(null=True, upload_to='uploads/Seller/'),
        ),
    ]
