# Generated by Django 5.0.1 on 2024-03-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_login', '0005_seller_proof_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='seller',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
